# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/users/muenzaniso/desktop/pycharmprojects/pqt4/dispensinpage.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.surna = QtWidgets.QLabel(self.centralwidget)
        self.surna.setGeometry(QtCore.QRect(50, 20, 47, 13))
        self.surna.setObjectName("surna")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(50, 50, 47, 13))
        self.name.setObjectName("name")
        self.dob = QtWidgets.QLabel(self.centralwidget)
        self.dob.setGeometry(QtCore.QRect(50, 80, 47, 13))
        self.dob.setObjectName("dob")
        self.phone = QtWidgets.QLabel(self.centralwidget)
        self.phone.setGeometry(QtCore.QRect(50, 110, 47, 13))
        self.phone.setObjectName("phone")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 50, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 80, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 110, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 0, 211, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.med_aid = QtWidgets.QLabel(self.centralwidget)
        self.med_aid.setGeometry(QtCore.QRect(280, 20, 47, 13))
        self.med_aid.setObjectName("med_aid")
        self.med_aid_no = QtWidgets.QLabel(self.centralwidget)
        self.med_aid_no.setGeometry(QtCore.QRect(280, 50, 47, 13))
        self.med_aid_no.setObjectName("med_aid_no")
        self.med_pack = QtWidgets.QLabel(self.centralwidget)
        self.med_pack.setGeometry(QtCore.QRect(280, 80, 47, 13))
        self.med_pack.setObjectName("med_pack")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(280, 110, 47, 13))
        self.title.setObjectName("title")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(340, 20, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(340, 50, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(340, 80, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(340, 110, 113, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 0, 201, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 10, 47, 13))
        self.label_9.setObjectName("label_9")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(620, 110, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(40, 160, 751, 231))
        self.tableView.setObjectName("tableView")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(620, 40, 101, 61))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(600, 10, 160, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 420, 47, 13))
        self.label.setObjectName("label")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(90, 420, 271, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 420, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(440, 420, 113, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 470, 47, 13))
        self.label_3.setObjectName("label_3")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(90, 460, 461, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(590, 420, 47, 13))
        self.label_4.setObjectName("label_4")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(650, 410, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 460, 47, 13))
        self.label_5.setObjectName("label_5")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(650, 450, 113, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 150, 771, 251))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 410, 761, 80))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 510, 75, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 512, 75, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 512, 75, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 512, 75, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 512, 75, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(580, 512, 75, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(680, 512, 75, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(30, 500, 741, 80))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.surna.setBuddy(self.lineEdit)
        self.name.setBuddy(self.lineEdit_2)
        self.dob.setBuddy(self.lineEdit_3)
        self.phone.setBuddy(self.lineEdit_4)
        self.med_aid.setBuddy(self.lineEdit_5)
        self.med_aid_no.setBuddy(self.lineEdit_6)
        self.med_pack.setBuddy(self.lineEdit_7)
        self.title.setBuddy(self.lineEdit_8)
        self.label.setBuddy(self.lineEdit_9)
        self.label_2.setBuddy(self.lineEdit_10)
        self.label_3.setBuddy(self.lineEdit_11)
        self.label_5.setBuddy(self.lineEdit_13)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.surna.setText(_translate("MainWindow", "Surname"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.dob.setText(_translate("MainWindow", "Date of Birth"))
        self.phone.setText(_translate("MainWindow", "Phone"))
        self.med_aid.setText(_translate("MainWindow", "Medical Aid"))
        self.med_aid_no.setText(_translate("MainWindow", "Medical Aid Number"))
        self.med_pack.setText(_translate("MainWindow", "Medical Aid Package"))
        self.title.setText(_translate("MainWindow", "Title"))
        self.label_9.setText(_translate("MainWindow", "TOTAL VALUE"))
        self.label.setText(_translate("MainWindow", "Drug"))
        self.label_2.setText(_translate("MainWindow", "Quanity"))
        self.label_3.setText(_translate("MainWindow", "Dosage"))
        self.label_4.setText(_translate("MainWindow", "Shortfall"))
        self.label_5.setText(_translate("MainWindow", "Cost"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton_2.setText(_translate("MainWindow", "Quote"))
        self.pushButton_3.setText(_translate("MainWindow", "Dispense"))
        self.pushButton_4.setText(_translate("MainWindow", "Preview"))
        self.pushButton_5.setText(_translate("MainWindow", "Settings"))
        self.pushButton_6.setText(_translate("MainWindow", "Help"))
        self.pushButton_7.setText(_translate("MainWindow", "Placeholder"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mainwindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Mainwindow)
    Mainwindow.show()
    sys.exit(app.exec_())