# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pagedispense.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.surname = QtWidgets.QLabel(self.centralwidget)
        self.surname.setObjectName("surname")
        self.gridLayout.addWidget(self.surname, 0, 0, 1, 1)
        self.surname_linedit = QtWidgets.QLineEdit(self.centralwidget)
        self.surname_linedit.setObjectName("surname_linedit")
        self.gridLayout.addWidget(self.surname_linedit, 0, 1, 1, 1)
        self.med_aid = QtWidgets.QLabel(self.centralwidget)
        self.med_aid.setObjectName("med_aid")
        self.gridLayout.addWidget(self.med_aid, 0, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 3, 1, 1)
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 1)
        self.name_linedit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_linedit.setObjectName("name_linedit")
        self.gridLayout.addWidget(self.name_linedit, 1, 1, 1, 1)
        self.med_aid_no = QtWidgets.QLabel(self.centralwidget)
        self.med_aid_no.setObjectName("med_aid_no")
        self.gridLayout.addWidget(self.med_aid_no, 1, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 3, 1, 1)
        self.dob = QtWidgets.QLabel(self.centralwidget)
        self.dob.setObjectName("dob")
        self.gridLayout.addWidget(self.dob, 2, 0, 1, 1)
        self.lineEdit_ = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_.setObjectName("lineEdit_")
        self.gridLayout.addWidget(self.lineEdit_, 2, 1, 1, 1)
        self.med_pack = QtWidgets.QLabel(self.centralwidget)
        self.med_pack.setObjectName("med_pack")
        self.gridLayout.addWidget(self.med_pack, 2, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 2, 3, 1, 1)
        self.phone = QtWidgets.QLabel(self.centralwidget)
        self.phone.setObjectName("phone")
        self.gridLayout.addWidget(self.phone, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 3, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 3, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 4, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_2.addWidget(self.timeEdit, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 5, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 1, 3, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 4, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_3.addWidget(self.lineEdit_10, 1, 3, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 2, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 4, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_3.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 1, 5, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_3.addWidget(self.lineEdit_13, 2, 5, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 0, 0, 1, 6)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 3, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 3, 5, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(102, 80))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(102, 80))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(102, 80))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(102, 80))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(102, 80))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(102, 80))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 0, 5, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(102, 80))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_4.addWidget(self.pushButton_7, 0, 6, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 4, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 934, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.surname.setBuddy(self.surname_linedit)
        self.med_aid.setBuddy(self.lineEdit_5)
        self.name.setBuddy(self.name_linedit)
        self.med_aid_no.setBuddy(self.lineEdit_6)
        self.dob.setBuddy(self.lineEdit_)
        self.med_pack.setBuddy(self.lineEdit_7)
        self.phone.setBuddy(self.lineEdit_4)
        self.title.setBuddy(self.lineEdit_8)
        self.label_9.setBuddy(self.textEdit)
        self.label_2.setBuddy(self.lineEdit_10)
        self.label_4.setBuddy(self.lineEdit_12)
        self.label_5.setBuddy(self.lineEdit_13)
        self.label_3.setBuddy(self.lineEdit_11)
        self.label.setBuddy(self.lineEdit_9)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.surname.setText(_translate("MainWindow", "Sur&name"))
        self.med_aid.setText(_translate("MainWindow", "Medical Aid"))
        self.name.setText(_translate("MainWindow", "N&ame"))
        self.med_aid_no.setText(_translate("MainWindow", "Medical Aid Number"))
        self.dob.setText(_translate("MainWindow", "Date of B&irth"))
        self.med_pack.setText(_translate("MainWindow", "Medical Aid Package"))
        self.phone.setText(_translate("MainWindow", "Phone"))
        self.title.setText(_translate("MainWindow", "Title"))
        self.label_9.setText(_translate("MainWindow", "TOTAL VALUE"))
        self.label_2.setText(_translate("MainWindow", "Quanity"))
        self.label_4.setText(_translate("MainWindow", "Shortfall"))
        self.label_5.setText(_translate("MainWindow", "Cost"))
        self.label_3.setText(_translate("MainWindow", "Dosage"))
        self.label.setText(_translate("MainWindow", "Drug"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton_2.setText(_translate("MainWindow", "Quote"))
        self.pushButton_3.setText(_translate("MainWindow", "Dispense"))
        self.pushButton_4.setText(_translate("MainWindow", "Preview"))
        self.pushButton_5.setText(_translate("MainWindow", "Settings"))
        self.pushButton_6.setText(_translate("MainWindow", "Help"))
        self.pushButton_7.setText(_translate("MainWindow", "Placeholder"))

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):

    def __init__(self, parent=None):
        QtWidgets.QMainWindow.__init__(self, parent=parent)
        self.setupUi(self)

    def keyPressEvent(self, event):
        key = event.key()
        if key == QtCore.Qt.Key_Escape:
            self.close()



    def mousePressEvent(self, QMouseEvent):
        #print(QMouseEvent.pos())
        cursor = QtGui.QCursor()
        print(cursor.pos())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = MainWindow()
    MainWindow.show()
    sys.exit(app.exec_())
